- project:
    check:
      jobs:
        - opendev-buildset-registry
        - nebulous-optimiser-resource-auction-agent-helm-lint
        - nebulous-optimiser-resource-auction-agent-build-container-images
        - nebulous-optimiser-resource-auction-agent-hadolint
        - nebulous-platform-apply-helm-charts
        - nox-linters
    gate:
      jobs:
        - opendev-buildset-registry
        - nebulous-optimiser-resource-auction-agent-helm-lint
        - nebulous-optimiser-resource-auction-agent-upload-container-images
        - nebulous-optimiser-resource-auction-agent-hadolint
        - nebulous-platform-apply-helm-charts
        - nox-linters
    promote:
      jobs:
        - nebulous-optimiser-resource-auction-agent-promote-container-images
